const details = {
	"design":{
		"waxlogo":{
			"title":"Wax Audio",
			"description":"Logo design for <i>Wax Audio</i>, a musician and mash-up artist.<br><br>The microphone and headphones are arranged to resemble the <i>hammer and sickle</i> symbol.",
		},
		"honey_label":{
			"title":"G&G's",
			"description":"Honey label design for an independent beekeeper, shown on a 3D model created using <i>Blender</i>.",
		},
		"heavensnight":{
			"title":"Heaven's Night",
			"description":"A fan-art re-creation of a neon sign that appears in the video game <i>Silent Hill 2</i>. 3D model created using <i>Blender</i>.",
		},
		"oana":{
			"title":"OANA",
			"description":"Logo design for OANA. The Organization of Asia-Pacific News Agencies.",
		},
		"neonsign":{
			"title":"Neon Sign",
			"description":"Neon sign comprising Chinese characters, set on a brick wall. 3D model created using <i>Blender</i>.",
		},
		"RANZCRNIVAL":{
			"title":"RANZCRNIVAL",
			"description":"Poster promoting a social event at RANZCR (Royal Australian and New Zealand College of Radiologists).",
		},
		"dirtyglass":{
			"title":"The Dirty Glass",
			"description":"Comic strip style illustration of the song <i>The Dirty Glass</i> by <i>Dropkick Murphys</i>. Verses of the song are depicted in the characters' speech bubbles while the lettering bordering the panels repeats the songs chorus.",
		},
		"tropdoc":{
			"title":"TropDoc",
			"description":"Poster promoting a short documentary film festival, the theme for the year being travel.",
		},
		"dce":{
			"title":"DCE",
			"description":"Poster promoting an open day event at Design Centre Enmore.",
		},
		"invitation":{
			"title":"Invitation",
			"description":"Wedding invitation, place card and wishing well note.",
		},
	},
	"infographic":{
		"kyrgios-nadal":{
			"title":"Kyrgios vs Nadal",
			"description":"How Nick Kyrgios and Rafael Nadal compare ahead of their fourth-round Australian Open 2020 match on Monday January 27.<br><br>Published 25/01/2020",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"COVID19-symptoms":{
			"title":"COVID-19 Symtoms",
			"description":"Graphic showing common symptom and rates of appearance in cases of Coronavirus COVID19. Based on information from the World Health Organization in early March 2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"DST_ByState_Islands-01":{
			"title":"Daylight Saving Time",
			"description":"Graphic showing the difference in time zones across Australia. Includes changes for daylight saving time ending Sunday April 5 2020 and shows time zones for Australian island and Antarctic territories.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"parliament":{
			"title":"Parliamentary Leadership Changes",
			"description":"Infographic showing changes to parliament as federal politicians return to Canberra for the first sitting week in 2020.<br><br>Published 04/02/2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"melbourne-lockdown":{
			"title":"Melbourne Lockdown",
			"description":"A timeline of key events leading to Melbourne and Mitchell Shire to again be placed into stage-three lockdowns.<br><br>Published 10/07/2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		
		"transport":{
			"title":"NSW Public Transport",
			"description":"The NSW government has revealed how public transport will run during COVID-19.<br><br>Published 18/05/2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"ABS_200505":{
			"title":"Virus Households",
			"description":"Inforaphic showing the financial impacts of COVID-19 on Australian households. Data released by Australian Bureau of Statistics May 5 2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"coal-power-stations":{
			"title":"Coal Power Stations",
			"description":"Infographic showing locations of Australia's largest coal power stations with chart displaying volumes of electricity generated by different sources.<br><br>Published 12/02/2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"aviation":{
			"title":"Aviation",
			"description":"Inforaphic showing statistics for aviation incidents in Australia from 2010 to 2019 across commercial, general and recreational flying.<br><br>Published 30/04/2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"budgetpreview_0722-01":{
			"title":"Federal Budget Update",
			"description":"Announcements and figures expected for the July 2020 economic and fiscal forecasts, ahead of a full federal budget in October.<br><br>Published 22/07/2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"nuclear-kimba":{
			"title":"Nuclear Waste",
			"description":"Map graphic showing locations of South Australian towns, Kimba and Wallerberdina in relation to Adelaide. Two sites are proposed for a nuclear waste dump near Kimba, on the Eyre Peninsula with another site in the Flinders Ranges being ruled out.<br><br>Published 31/01/2020.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"COVIDHOTSPOTS-01":{
			"title":"COVID-19 Hotspots, Victoria",
			"description":"Map showing local council areas in Victoria considered COVID-19 hotspots in late June 2020.<br><br>Published 22/06/2020",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
	},
	"interactive":{
		"election": {
			"url":"//hosted.aap.com.au/interactives/election_2019/houseofreps/index.html",
			"title":"Federal Election",
			"description":"Interactive graphic for the 2019 federal election. Displays the state of the parliament prior to, and following May 18 2019.<br><br>The pre-election 'Swing-O-Meter' simulates a swing of ten percent toward the government or opposition based on two-party-preferred margins. The yellow stars appearing on icons represent a seat won. Clicking on each icon reveals information about that electorate.<br><br>Each electorate can be selected from the drop-down menu, highlighting it's icon in the main section. The results were updated continuously on election night.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"covid": {
			"url":"//hosted.aap.com.au/interactives/covid19/index.html",
			"title":"COVID-19 Diary",
			"description":"A daily snapshot of COVID-19 figures by Australian state and territory, and approximate worldwide figures. Beginning January 25 2020 and continuing to July 31 2020.<br><br>Includes image gallery with photos capturing significant moments and daily life during the pandemic.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"tdf": {
			"url":"//hosted.aap.com.au/interactives/tourdefrance_2016/index.html",
			"title":"Tour De France",
			"description":"An interactive guide to the stages of the 2016 Tour De France. The route of each stage is plotted out using the Google Maps API and shown with elevation profiles. Also featured is team information and race results.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"season": {
			"url":"//hosted.aap.com.au/interactives/nrl_19/index.html",
			"title":"NRL Season Guide",
			"description":"Interactive graphic for the 2019 NRL season. Featuring match fixtures, scores and details on each game. Also includes season ladder and team head-to-head comparisons.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"grandfinal": {
			"url":"//hosted.aap.com.au/interactives/grandfinal_19/nrl/index.html",
			"title":"NRL Grand Final",
			"description":"Interactive graphic showing player stats & profiles in the 2019 Rugby League grand final. Scores & stats update following half time & full time via JSON data feed.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"memory": {
			"url":"//hosted.aap.com.au/interactives/memory/index.html?g=harry",
			"title":"Memory Game",
			"description":"A pair-matching memory game themed around royal couples, made in the lead up to Prince Harry and Meghan Markle's 2018 wedding.<br><br>The objective is to match the cards for the royal couples. The game can be played solo, against another person or against the computer, with two difficulty options.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"nzelection": {
			"url":"//hosted.aap.com.au/interactives/nzelection2014/stateoftheparliament/index.html",
			"title":"New Zealand Election",
			"description":"Infographic for the 2014 New Zealand election. The coloured hexagons represent seats won by Labour, National or crossbench candidates.<br><br>Clicking on coloured hexagons reveals inforation about that electorate. The hexagon design is to represent the inside of a beehive, to match the nickname of New Zealand's parliament house.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"tennis": {
			"url":"//hosted.aap.com.au/interactives/tennis_20/index.html?t=au",
			"title":"Australian Open",
			"description":"An interactive graphic for the 2020 Australian Open tennis tournament.<br><br>Includes fixtures and results, profiles of selected top ranked and Australian players and grand slam singles finals records from 1968 to 2020.<br><br>Fixtures and match results updated via data feeds.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"racing": {
			"url":"//hosted.aap.com.au/interactives/springcarnival2019/index.html?domain=aap&meeting=mel",
			"title":"Spring Racing",
			"description":"Interactive graphic for the 2019 spring racing carnival. Includes form guide info for each race at eight meetings during the spring racing season.<br><br>Clicking each row expands it, revealing form guide info for each horse.<br><br>Also includes an interactive sweep form for the Melbourne Cup. The sweep form calculates prize pools and randomises draws and can be printed.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
	},
	"video":{
		"augusta": {
			"title":"Augusta",
			"description":"An animated hole by hole fly through of the Augusta golf course, created using Google Earth Studio.<br><br>The pin flags for each hole were then added using Adobe After Effects.",
			"disclaimer":"",
		},
		"m4tunnel": {
			"title":"M4 Tunnel Opening",
			"description":"A video made using the custom <i>VidEx</i>&nbsp;application That I created for quick production of video, compiling still photography, footage and caption overlays.<br><br>Features animation created using Google Earth Studio, combined with overlays made with KML, showing the approximate route of the M4 tunnel between Homebush and Haberfield next to the existing route along Parramatta Road.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"apollo11": {
			"title":"Apollo 11",
			"description":"An animation created in Google Earth Studio for use in a video about the anniversary of the Apollo 11 mission.<br><br>The Saturn V rocket illustration was made in Adobe Illustrator, then animated and superimposed using Adobe After Effects.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"sharks": {
			"title":"Sharks",
			"description":"A video about shark related deaths in Australia.<br><br>Features animation created using Google Earth Studio. Animated location markers were added using Adobe After Effects.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
		"chineseship": {
			"title":"Chinese Warship",
			"description":"A video about the arrival of a Chinese warship in Sydney Harbour.<br><br>Features animation created using Google Earth Studio, showing the location of the Garden Island Naval Base in Sydney.",
			"disclaimer":"displayed content &#169 Australian Associated Press",
		},
	},
};